version: '3.9'

services:
  postgres:
    image: postgres
    container_name: database-postgres
    restart: unless-stopped
    hostname: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ${PG_DATA_PATH}:/var/lib/postgresql/data
      - ${SCRIPT_PATH}:/docker-entrypoint-initdb.d  # Automatically run scripts on initialization
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

volumes:
  postgres_data:
